### ISSUE TITLE
Relation to BIDS

### ISSUE THREAD

**Issue by jbpoline** [INCF/neuroscience-data-structure#1]
Quick thought for discussion : it would be interesting to see how this can piggybag on BIDS, but also how it can go beyond with a formal schema / linked technology components

**Comment by SylvainTakerkart** [comment]
Hi JB,
Thanks for the feedback!
The aim of this repo (and the project that goes with it, which will see soon an application to become an INCF SIG) is to try to standardize a data structure for animal experiments, similarly to what BIDS offers for human data. 
We've launched the reflexion earlier this year, had a meeting in the spring with an extended group from numerous institutions worldwide (including members of the BIDS steering committee) to identify several issues to discuss ("inside or outside of BIDS" being one of them). So, we will explain all this very soon... And we'll of course welcome contributions from anybody who might be interested...
Soooooo, the bottomline is: info coming soon! ;)

**Comment by jbpoline** [comment]
Awesome ! looking forward to it, and let me know if I can help in anyways
through the INCF CTSI
cheers
JB

**Comment by jcolomb** [comment]
linking https://github.com/bids-standard/bids-2-devel/issues/38 (bids for animal data)
for further discussion.
